# Version of the AppSpec file. This is required.
version: 0.0

# Specify the operating system. Use 'linux' for EC2 Linux instances and 'windows' for Windows.
os: linux

#  A directory bundle is uploaded and contains a structure like this:

# src/
# ├── index.html
# ├── app.js
# config/
# └── nginx.conf

# Define the source files and their destination on the target instance.
files:
  # Copy the web application files from the source bundle to the web server directory.
  - source: /src
    destination: /var/www/html

  # Copy configuration files (e.g., Nginx or Apache configs) to the appropriate directory.
  - source: /config/nginx.conf
    destination: /etc/nginx/conf.d

# Define permissions for copied files if required (optional).
permissions:
  - object: /var/www/html
    pattern: "**/*" # All files and directories recursively under /var/www/html.
    owner: www-data # www-data is a common user for web servers
    group: www-data
    mode: 755
    type:
      - file
      - directory
      
# * matches any file or directory in the current level.
# ** matches files and directories recursively in all subdirectories.

# Define hooks to run scripts at various stages of the deployment lifecycle.
hooks:
  # Runs before any application files are copied.
  BeforeInstall:
    - location: scripts/clean_previous.sh
      timeout: 300
      runas: root

  # Runs after the application files are copied but before the application is started.
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root

  # Runs to start or restart the application after installation.
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  # Runs as a validation step to ensure the deployment was successful.
  ValidateService:
    - location: scripts/validate_deployment.sh
      timeout: 300
      runas: root
