version: 0.2

env:
  variables:
    ENVIRONMENT: "production"
    APP_NAME: "my-cool-app"
  secrets-manager:
    DB_PASSWORD: "my-secret/db-password"

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - echo "Installing dependencies for the build environment..."
      - pip install --upgrade pip
      - apt-get update && apt-get install -y jq
  pre_build:
    commands:
      - echo "Running pre-build checks and setup..."
      - pip install -r requirements.txt
      - npm install
      - echo "All dependencies installed successfully."
  build:
    commands:
      - echo "Building and testing the application..."
      - python -m unittest discover tests
      - npm run build
      - echo "Build process completed successfully."
  post_build:
    commands:
      - echo "Starting deployment..."
      - aws s3 cp ./frontend/build s3://my-cool-app-bucket --recursive
      - aws ecs update-service --cluster my-app-cluster --service my-app-service --force-new-deployment
      - echo "Deployment completed."

artifacts:
  files:
    - 'frontend/build/**/*'
    - 'backend/**/*.py'
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - 'node_modules/**/*'
